# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desination',
            new_name='Destination',
        ),
    ]
