# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_auto_20170726_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destination',
            new_name='name',
        ),
    ]
