# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_auto_20170726_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='location',
        ),
    ]
