# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_auto_20170726_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_date_from',
            field=models.DateField(default=['%m/%d/%Y']),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_date_to',
            field=models.DateField(default=['%m/%d/%Y']),
        ),
    ]
